# Generated by Django 4.0.9 on 2024-10-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('mobile_no', models.CharField(max_length=50, null=True)),
                ('department', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
