# Generated by Django 4.0.9 on 2024-10-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='accept',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='reject',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='rh_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
