# Generated by Django 4.0.9 on 2024-10-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_registration_accept_registration_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='type_of_pain',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
