# Generated by Django 4.0.9 on 2024-10-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_pain_relief'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='type_of_pain',
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='type_of_pain',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
