# Generated by Django 4.0.9 on 2024-10-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_alter_pain_relief_b_stiffness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='cl_login',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
