# Generated by Django 4.0.9 on 2024-10-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_registration_cl_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='pain_relief',
            name='rh_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
