# Generated by Django 4.0.9 on 2024-11-04 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_registration_cl_logout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pain_relief',
            name='project_id',
        ),
    ]
