# Generated by Django 4.0.9 on 2024-11-04 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0010_remove_pain_relief_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pain_relief',
            old_name='swelpain_with_certain_movementsling',
            new_name='pain_with_certain_movements',
        ),
    ]
