# Generated by Django 4.0.9 on 2024-11-04 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0011_rename_swelpain_with_certain_movementsling_pain_relief_pain_with_certain_movements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pain_relief',
            old_name='rh_id',
            new_name='cl_rh_id',
        ),
    ]
