# Generated by Django 4.0.9 on 2024-11-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0012_rename_rh_id_pain_relief_cl_rh_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='bp',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='kp',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
