# Generated by Django 4.0.9 on 2024-11-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0013_registration_bp_registration_kp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pain_relief',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
