# Generated by Django 4.0.9 on 2024-11-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0015_remove_registration_cl_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pain_relief',
            name='cl_login',
        ),
        migrations.RemoveField(
            model_name='pain_relief',
            name='cl_logout',
        ),
        migrations.AddField(
            model_name='registration',
            name='cl_login',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='cl_logout',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
