# Generated by Django 4.0.9 on 2024-11-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0016_remove_pain_relief_cl_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pain_relief',
            name='client_login',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='client_logout',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
