# Generated by Django 4.0.9 on 2024-11-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0017_pain_relief_client_login_pain_relief_client_logout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registration',
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='accept',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='bp',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='cl_login',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='cl_logout',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='kp',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='mobile_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='reject',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='rh_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
