# Generated by Django 4.0.9 on 2024-11-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0018_delete_registration_pain_relief_accept_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('mobile_no', models.CharField(max_length=50, null=True)),
                ('department', models.CharField(max_length=50, null=True)),
                ('rh_id', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('accept', models.BooleanField(default=False, null=True)),
                ('reject', models.BooleanField(default=False, null=True)),
                ('cl_login', models.BooleanField(default=False, null=True)),
                ('cl_logout', models.BooleanField(default=False, null=True)),
                ('kp', models.BooleanField(default=False, null=True)),
                ('bp', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pain_relief',
            name='accept',
        ),
        migrations.RemoveField(
            model_name='pain_relief',
            name='bp',
        ),
        migrations.RemoveField(
            model_name='pain_relief',
            name='cl_login',
        ),
        migrations.RemoveField(
            model_name='pain_relief',
            name='cl_logout',
        ),
        migrations.RemoveField(
            model_name='pain_relief',
            name='department',
        ),
        migrations.RemoveField(
            model_name='pain_relief',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pain_relief',
            name='kp',
        ),
        migrations.RemoveField(
            model_name='pain_relief',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='pain_relief',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pain_relief',
            name='password',
        ),
        migrations.RemoveField(
            model_name='pain_relief',
            name='reject',
        ),
        migrations.RemoveField(
            model_name='pain_relief',
            name='rh_id',
        ),
    ]
