# Generated by Django 4.0.9 on 2024-11-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0019_registration_remove_pain_relief_accept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pain_relief',
            name='status',
            field=models.CharField(default='Pending', max_length=50, null=True),
        ),
    ]
