# Generated by Django 4.0.9 on 2024-11-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0020_alter_pain_relief_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pain_relief',
            name='ef_scan',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='pm_scan',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='rt_scan',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
