# Generated by Django 4.0.9 on 2024-11-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0021_pain_relief_ef_scan_pain_relief_pm_scan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pain_relief',
            old_name='muscle_spams',
            new_name='muscle_spasms',
        ),
    ]
