# Generated by Django 4.0.9 on 2024-11-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0022_rename_muscle_spams_pain_relief_muscle_spasms'),
    ]

    operations = [
        migrations.AddField(
            model_name='pain_relief',
            name='severity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='type_of_backpain',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='type_of_kneepain',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
