# Generated by Django 4.0.9 on 2024-11-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0023_pain_relief_severity_pain_relief_type_of_backpain_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pain_relief',
            old_name='ef_scan',
            new_name='ef_bp_scan',
        ),
        migrations.RenameField(
            model_name='pain_relief',
            old_name='pm_scan',
            new_name='pm_bp_scan',
        ),
        migrations.RenameField(
            model_name='pain_relief',
            old_name='rt_scan',
            new_name='pm_kp_scan',
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='ef_kp_scan',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='rt_bp_scan',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='rt_kp_scan',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
