# Generated by Django 4.0.9 on 2024-11-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0024_rename_ef_scan_pain_relief_ef_bp_scan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pain_relief',
            name='duration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='therapy',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
