# Generated by Django 4.0.9 on 2024-11-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0025_pain_relief_duration_pain_relief_therapy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='bp',
            new_name='back_pain',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='kp',
            new_name='knee_pain',
        ),
    ]
