# Generated by Django 4.0.9 on 2024-11-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0026_rename_bp_registration_back_pain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pain_relief',
            name='r_b_stiffness',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='r_bearing_weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='r_fatigue',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='r_fever_or_chills',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='r_limited_range_of_motion',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='r_loss_of_range_of_motion',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='r_muscle_spams',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='r_numbness_or_tingling',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='r_overall_relief_preception',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='r_pain_intensity_after_therapy',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='r_pain_intensity_before_therapy',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='r_pain_that_worsens_at_night',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='r_pain_with_certain_movements',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='r_pain_with_movement',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='r_popping_or_grinding_sensation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='r_radiating_pain',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='r_stiffness',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='r_swelling',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='r_tenderness',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='r_warmth_and_redness',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='r_weakness_or_instability',
            field=models.IntegerField(null=True),
        ),
    ]
