# Generated by Django 4.0.9 on 2024-11-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0027_pain_relief_r_b_stiffness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='r_back_pain',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='r_knee_pain',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
