# Generated by Django 4.0.9 on 2024-11-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0028_registration_r_back_pain_registration_r_knee_pain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='r_back_pain',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='r_knee_pain',
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='r_back_pain',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='r_knee_pain',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
