# Generated by Django 4.0.9 on 2024-11-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0029_remove_registration_r_back_pain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pain_relief',
            name='effectiveness',
            field=models.IntegerField(null=True),
        ),
    ]
