# Generated by Django 4.0.9 on 2024-11-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0030_pain_relief_effectiveness'),
    ]

    operations = [
        migrations.AddField(
            model_name='pain_relief',
            name='bp_f_rep_view',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='bp_f_report',
            field=models.FileField(blank=True, null=True, upload_to='final_report/'),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='kp_f_rep_view',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='pain_relief',
            name='kp_f_report',
            field=models.FileField(blank=True, null=True, upload_to='final_report/'),
        ),
    ]
