# Generated by Django 4.0.9 on 2024-11-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0032_alter_pain_relief_bp_f_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pain_relief',
            name='bp_f_report',
            field=models.FileField(blank=True, null=True, upload_to='bp_final_report/'),
        ),
        migrations.AlterField(
            model_name='pain_relief',
            name='kp_f_report',
            field=models.FileField(blank=True, null=True, upload_to='kp_final_report/'),
        ),
    ]
